apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api
spec:
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
      - name: db-api
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: password
        image: docker.io/isaaccollins/isaac-watermark:db-api1
        ports:
        - containerPort: 5000
