apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api
spec:
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
      - name: db-api
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: password
        - name: DB_USER
          value: root
        - name: DB_HOST
          value: mysqldb-svc
        image: docker.io/isaaccollins/isaac-watermark:db-api$BUILD_NUMBER
        ports:
        - containerPort: 5000
