apiVersion: v1
kind: Service 
metadata:
  name: backend-svc
  labels:
    tier: backend
    app: watermark
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
   label: backend
   app: watermark