
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: watermark
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: watermark
      tier: frontend
  template:
    metadata:
      labels:
        app: watermark
        tier: frontend
    spec:
      containers:
      - name: frontend-app
        image: docker.io/isaaccollins/isaac-watermark:frontend{{ .Values.image.tag }}
        ports:
        - containerPort: 80