---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "*.elb.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: ingress-watermark
            port:
              number: 80
      - path: /api/transform
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 80