
apiVersion: v1
kind: Service
metadata:
  name: ingress-watermark
  labels:
    app: watermark
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    tier: frontend