name: Deploy to EKS
on: 
  push:
    branches:
      - test

jobs:
  kubernetes:
    name: Apply Manifests EKS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "manifest"
        
    steps: 
    - uses: actions/checkout@v2

    - name: Config AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-west-2

    - name: Update KubeConfig
      run: aws eks --region us-west-2 update-kubeconfig --name k8s-watermark

    - name: Add Container Build Numbers
      run: sed -i 's/$BUILD_NUMBER/1/' *

    - name: Apply Manifests
      run: kubectl apply -f .
      
    - name: Return LoadBalancer IP
      run: bash -c 'external_ip=""; while [ -z $external_ip ]; do echo "Waiting for end point..."; external_ip=$(kubectl get svc ingress-watermark --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}"); [ -z "$external_ip" ] && sleep 10; done; echo "Ingress IP ready - " && echo $external_ip; export endpoint=$external_ip'

